# Generated by Django 3.0.7 on 2020-08-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('fpred', models.CharField(default='-1', max_length=1)),
                ('paddress', models.TextField()),
                ('password', models.CharField(max_length=100)),
                ('doctor', models.BooleanField(default=False)),
            ],
        ),
    ]
