# Generated by Django 3.0.7 on 2020-08-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('married', models.CharField(max_length=3)),
                ('depend', models.CharField(max_length=2)),
                ('education', models.CharField(max_length=12)),
                ('self_employ', models.CharField(max_length=3)),
                ('aincome', models.IntegerField()),
                ('caincome', models.IntegerField()),
                ('loanamt', models.IntegerField()),
                ('loanterm', models.IntegerField()),
                ('credhist', models.IntegerField()),
                ('area', models.CharField(max_length=9)),
                ('pred', models.CharField(default='-1', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
